# 复制此文件为 local.py 并填写真实值
# Copy this file to local.py and fill in your values

APP_ID = "cli_xxxxxxxxxxxxxxxx"
APP_SECRET = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

NOTIFY_CHAT_ID = ""
NOTIFY_OPEN_ID = ""

OPENAI_API_KEY = "sk-xxxxxxxxxxxxxxxx"
OPENAI_BASE_URL = ""
OPENAI_MODEL = "gpt-5.4"
OPENAI_TIMEOUT = 600
AGENTS_PATH = ""

FEISHU_CLI_ENABLED = False
FEISHU_CLI_BIN = "lark-cli"
FEISHU_CLI_AS = ""
FEISHU_CLI_TIMEOUT = 120
FEISHU_CLI_EXTRA_ARGS = []

DOC_IMPORT_ENABLED = False
DOC_IMPORT_DIR = ""
DOC_IMPORT_POLL_SECONDS = 10
DOC_IMPORT_STABLE_SECONDS = 5
DOC_IMPORT_CLI_AS = "bot"
DOC_IMPORT_FOLDER_TOKEN = ""
DOC_IMPORT_WIKI_NODE = ""
DOC_IMPORT_WIKI_SPACE = ""
DOC_IMPORT_NOTIFY_CHAT_ID = ""
DOC_IMPORT_NOTIFY_OPEN_ID = ""

AGENT_NOTIFY_ENABLED = True
AGENT_NOTIFY_DIR = ""
AGENT_NOTIFY_POLL_SECONDS = 5
AGENT_NOTIFY_STABLE_SECONDS = 2
AGENT_NOTIFY_CHAT_ID = ""
AGENT_NOTIFY_OPEN_ID = ""

AGENT_RUNNER_ENABLED = True
AGENT_RUNNER_DEFAULT_CWD = ""
AGENT_RUNNER_TIMEOUT_SECONDS = 3600
AGENT_RUNNER_MAX_CONCURRENT = 2
AGENT_RUNNER_CODEX_BIN = ""
AGENT_RUNNER_CLAUDE_BIN = ""
AGENT_RUNNER_CODEX_ARGS = ["exec", "--skip-git-repo-check", "--color", "never"]
AGENT_RUNNER_CLAUDE_ARGS = ["-p", "--permission-mode", "acceptEdits"]
AGENT_RUNNER_ALLOWED_SENDERS = []
